// Generated by jextract

package com.msgcore.native_;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*msgcore_trigger_fn)(void *, unsigned int, unsigned long long)
 * }
 */
public final class msgcore_trigger_fn {

    private msgcore_trigger_fn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment pUser, int nTriggerType, long p2pos);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        Msgcore_c.C_POINTER,
        Msgcore_c.C_INT,
        Msgcore_c.C_LONG_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Msgcore_c.upcallHandle(msgcore_trigger_fn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(msgcore_trigger_fn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment pUser, int nTriggerType, long p2pos) {
        try {
             DOWN$MH.invokeExact(funcPtr, pUser, nTriggerType, p2pos);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

