// Msgcore_c.java
// AUTO-GENERATED by jextract — do not edit by hand.
// Re-generate with:
//   jextract --output src/main/java \
//            --target-package com.msgcore.native_ \
//            --library Msgcore \
//            <path-to-Msgcore_c.h>
//
// This stub documents the expected jextract output shape so wrapper classes
// can compile before jextract is actually run.  Replace this file entirely
// with the real jextract output once the Msgcore DLL is built.
//
package com.msgcore.native_;

import java.lang.foreign.*;
import java.lang.invoke.*;

public final class Msgcore_c {

    private Msgcore_c() {}

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static {
        System.loadLibrary("Msgcore");
    }

    static final SymbolLookup SYMBOL_LOOKUP =
        SymbolLookup.libraryLookup(System.mapLibraryName("Msgcore"), LIBRARY_ARENA)
                    .or(SymbolLookup.loaderLookup())
                    .or(Linker.nativeLinker().defaultLookup());

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static final Linker LINKER = Linker.nativeLinker();

    // ------------------------------------------------------------------
    // Downcall handles — one per C function
    // ------------------------------------------------------------------

    private static final MethodHandle MH_msgcore_mgr_create =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_create"),
            FunctionDescriptor.of(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_create_nn =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_create_nn"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.JAVA_BYTE, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_mgr_open_file =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_open_file"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_load =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_load"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_save =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_save"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_nullify =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_nullify"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_rename =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_rename"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_get_filename =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_get_filename"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_get_rootname =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_get_rootname"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_is_dirty =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_is_dirty"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_set_dirty =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_set_dirty"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_mgr_sizeof =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_sizeof"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_is_valid =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_is_valid"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_mgr_as_field =
        LINKER.downcallHandle(findOrThrow("msgcore_mgr_as_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_create =
        LINKER.downcallHandle(findOrThrow("msgcore_field_create"),
            FunctionDescriptor.of(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_clone =
        LINKER.downcallHandle(findOrThrow("msgcore_field_clone"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_field_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_select_item =
        LINKER.downcallHandle(findOrThrow("msgcore_field_select_item"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_exists =
        LINKER.downcallHandle(findOrThrow("msgcore_field_exists"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_delete_item =
        LINKER.downcallHandle(findOrThrow("msgcore_field_delete_item"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_truncate =
        LINKER.downcallHandle(findOrThrow("msgcore_field_truncate"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_declare_int =
        LINKER.downcallHandle(findOrThrow("msgcore_field_declare_int"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_declare_int64 =
        LINKER.downcallHandle(findOrThrow("msgcore_field_declare_int64"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_declare_double =
        LINKER.downcallHandle(findOrThrow("msgcore_field_declare_double"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_declare_bool =
        LINKER.downcallHandle(findOrThrow("msgcore_field_declare_bool"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_declare_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_field_declare_wstr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_get_name =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_name"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_get_data_type =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_data_type"),
            FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_null =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_null"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_void =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_void"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_get_int =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_int"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_set_int =
        LINKER.downcallHandle(findOrThrow("msgcore_field_set_int"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_get_int64 =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_int64"),
            FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_set_int64 =
        LINKER.downcallHandle(findOrThrow("msgcore_field_set_int64"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));

    private static final MethodHandle MH_msgcore_field_get_double =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_double"),
            FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_set_double =
        LINKER.downcallHandle(findOrThrow("msgcore_field_set_double"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE));

    private static final MethodHandle MH_msgcore_field_get_bool =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_bool"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_set_bool =
        LINKER.downcallHandle(findOrThrow("msgcore_field_set_bool"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_field_get_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_field_get_wstr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_set_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_field_set_wstr"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_list =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_list"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_vect =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_vect"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_attributed =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_attributed"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_field_is_descendant =
        LINKER.downcallHandle(findOrThrow("msgcore_field_is_descendant"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // List
    private static final MethodHandle MH_msgcore_list_from_field =
        LINKER.downcallHandle(findOrThrow("msgcore_list_from_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_list_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_get_count =
        LINKER.downcallHandle(findOrThrow("msgcore_list_get_count"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_add_tail_int =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_tail_int"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_list_add_head_int =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_head_int"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_list_add_tail_double =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_tail_double"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE));

    private static final MethodHandle MH_msgcore_list_add_head_double =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_head_double"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE));

    private static final MethodHandle MH_msgcore_list_add_tail_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_tail_wstr"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_add_head_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_list_add_head_wstr"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_drop_head =
        LINKER.downcallHandle(findOrThrow("msgcore_list_drop_head"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_drop_tail =
        LINKER.downcallHandle(findOrThrow("msgcore_list_drop_tail"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_list_truncate =
        LINKER.downcallHandle(findOrThrow("msgcore_list_truncate"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    // Vect
    private static final MethodHandle MH_msgcore_vect_from_field =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_from_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_vect_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_vect_is_data =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_is_data"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_is_field =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_is_field"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_is_list =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_is_list"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_is_vect =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_is_vect"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_get_int =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_get_int"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_get_double =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_get_double"),
            FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_get_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_get_wstr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_get_item =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_get_item"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_vect_truncate =
        LINKER.downcallHandle(findOrThrow("msgcore_vect_truncate"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    // Attr
    private static final MethodHandle MH_msgcore_attr_from_field =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_from_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_attr_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_get_count =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_get_count"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_is_empty =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_is_empty"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_exists =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_exists"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_select_item =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_select_item"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_declare_int =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_declare_int"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_attr_declare_double =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_declare_double"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_attr_declare_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_declare_wstr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_attr_delete =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_delete"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_attr_truncate =
        LINKER.downcallHandle(findOrThrow("msgcore_attr_truncate"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    // Desc
    private static final MethodHandle MH_msgcore_desc_from_field =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_from_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_desc_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_get_count =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_get_count"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_is_empty =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_is_empty"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_exists =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_exists"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_select_item =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_select_item"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_declare_int =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_declare_int"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_desc_declare_wstr =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_declare_wstr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS,
                ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_desc_delete =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_delete"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_desc_truncate =
        LINKER.downcallHandle(findOrThrow("msgcore_desc_truncate"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    // Curs
    private static final MethodHandle MH_msgcore_curs_from_field =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_from_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_from_attr =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_from_attr"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_from_desc =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_from_desc"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_destroy =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_destroy"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_next =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_next"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_seek =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_seek"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_goto_name =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_goto_name"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_goto_index =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_goto_index"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    private static final MethodHandle MH_msgcore_curs_is_eo_cursor =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_is_eo_cursor"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_is_so_cursor =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_is_so_cursor"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_get_count =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_get_count"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_item_index =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_item_index"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_is_item =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_is_item"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_is_list =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_is_list"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_is_vect =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_is_vect"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_get_field =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_get_field"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_get_name =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_get_name"),
            FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_curs_delete =
        LINKER.downcallHandle(findOrThrow("msgcore_curs_delete"),
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));

    private static final MethodHandle MH_msgcore_wildcard_match =
        LINKER.downcallHandle(findOrThrow("msgcore_wildcard_match"),
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

    // ------------------------------------------------------------------
    // Wide-string helper: Java String <-> null-terminated UTF-16LE
    // ------------------------------------------------------------------

    public static MemorySegment toWStr(Arena arena, String s) {
        if (s == null) return MemorySegment.NULL;
        byte[] bytes = s.getBytes(java.nio.charset.StandardCharsets.UTF_16LE);
        MemorySegment seg = arena.allocate(bytes.length + 2);
        MemorySegment.copy(bytes, 0, seg, ValueLayout.JAVA_BYTE, 0, bytes.length);
        seg.set(ValueLayout.JAVA_SHORT, bytes.length, (short) 0);
        return seg;
    }

    public static String fromWStr(MemorySegment ptr) {
        if (ptr == null || ptr.equals(MemorySegment.NULL)) return null;
        // Scan for null terminator (2 zero bytes)
        MemorySegment unbounded = ptr.reinterpret(Long.MAX_VALUE);
        long len = 0;
        while (unbounded.get(ValueLayout.JAVA_SHORT, len * 2) != 0) len++;
        if (len == 0) return "";
        byte[] bytes = new byte[(int)(len * 2)];
        MemorySegment.copy(unbounded, ValueLayout.JAVA_BYTE, 0, bytes, 0, bytes.length);
        return new String(bytes, java.nio.charset.StandardCharsets.UTF_16LE);
    }

    // ------------------------------------------------------------------
    // Static API — mirrors every C function
    // ------------------------------------------------------------------

    public static MemorySegment msgcore_mgr_create() {
        try { return (MemorySegment) MH_msgcore_mgr_create.invokeExact(); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_mgr_create_nn(byte uAddrNN, int nSizeInitial, int nSizeMax) {
        try { return (MemorySegment) MH_msgcore_mgr_create_nn.invokeExact(uAddrNN, nSizeInitial, nSizeMax); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_mgr_open_file(MemorySegment filename) {
        try { return (MemorySegment) MH_msgcore_mgr_open_file.invokeExact(filename); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_mgr_destroy(MemorySegment hMgr) {
        try { MH_msgcore_mgr_destroy.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_load(MemorySegment hMgr, MemorySegment filename) {
        try { return (int) MH_msgcore_mgr_load.invokeExact(hMgr, filename); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_save(MemorySegment hMgr, MemorySegment filename) {
        try { return (int) MH_msgcore_mgr_save.invokeExact(hMgr, filename); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_mgr_nullify(MemorySegment hMgr) {
        try { MH_msgcore_mgr_nullify.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_rename(MemorySegment hMgr, MemorySegment newname) {
        try { return (int) MH_msgcore_mgr_rename.invokeExact(hMgr, newname); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_mgr_get_filename(MemorySegment hMgr) {
        try { return (MemorySegment) MH_msgcore_mgr_get_filename.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_mgr_get_rootname(MemorySegment hMgr) {
        try { return (MemorySegment) MH_msgcore_mgr_get_rootname.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_is_dirty(MemorySegment hMgr) {
        try { return (int) MH_msgcore_mgr_is_dirty.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_set_dirty(MemorySegment hMgr, int bDirty) {
        try { return (int) MH_msgcore_mgr_set_dirty.invokeExact(hMgr, bDirty); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_sizeof(MemorySegment hMgr) {
        try { return (int) MH_msgcore_mgr_sizeof.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_mgr_is_valid(MemorySegment hMgr) {
        try { return (int) MH_msgcore_mgr_is_valid.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_mgr_as_field(MemorySegment hMgr) {
        try { return (MemorySegment) MH_msgcore_mgr_as_field.invokeExact(hMgr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_create() {
        try { return (MemorySegment) MH_msgcore_field_create.invokeExact(); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_clone(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_field_clone.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_destroy(MemorySegment hField) {
        try { MH_msgcore_field_destroy.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_select_item(MemorySegment hField, MemorySegment name) {
        try { return (MemorySegment) MH_msgcore_field_select_item.invokeExact(hField, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_exists(MemorySegment hField, MemorySegment name) {
        try { return (int) MH_msgcore_field_exists.invokeExact(hField, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_delete_item(MemorySegment hField, MemorySegment name) {
        try { return (int) MH_msgcore_field_delete_item.invokeExact(hField, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_truncate(MemorySegment hField) {
        try { MH_msgcore_field_truncate.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_declare_int(MemorySegment h, MemorySegment name, int value, int bUpdate) {
        try { return (MemorySegment) MH_msgcore_field_declare_int.invokeExact(h, name, value, bUpdate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_declare_int64(MemorySegment h, MemorySegment name, long value, int bUpdate) {
        try { return (MemorySegment) MH_msgcore_field_declare_int64.invokeExact(h, name, value, bUpdate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_declare_double(MemorySegment h, MemorySegment name, double value, int bUpdate) {
        try { return (MemorySegment) MH_msgcore_field_declare_double.invokeExact(h, name, value, bUpdate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_declare_bool(MemorySegment h, MemorySegment name, int bValue, int bUpdate) {
        try { return (MemorySegment) MH_msgcore_field_declare_bool.invokeExact(h, name, bValue, bUpdate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_declare_wstr(MemorySegment h, MemorySegment name, MemorySegment value, int bUpdate) {
        try { return (MemorySegment) MH_msgcore_field_declare_wstr.invokeExact(h, name, value, bUpdate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_get_name(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_field_get_name.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static byte msgcore_field_get_data_type(MemorySegment hField) {
        try { return (byte) MH_msgcore_field_get_data_type.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_null(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_null.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_void(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_void.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_get_int(MemorySegment hField) {
        try { return (int) MH_msgcore_field_get_int.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_set_int(MemorySegment hField, int value) {
        try { MH_msgcore_field_set_int.invokeExact(hField, value); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static long msgcore_field_get_int64(MemorySegment hField) {
        try { return (long) MH_msgcore_field_get_int64.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_set_int64(MemorySegment hField, long value) {
        try { MH_msgcore_field_set_int64.invokeExact(hField, value); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static double msgcore_field_get_double(MemorySegment hField) {
        try { return (double) MH_msgcore_field_get_double.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_set_double(MemorySegment hField, double value) {
        try { MH_msgcore_field_set_double.invokeExact(hField, value); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_get_bool(MemorySegment hField) {
        try { return (int) MH_msgcore_field_get_bool.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_set_bool(MemorySegment hField, int bValue) {
        try { MH_msgcore_field_set_bool.invokeExact(hField, bValue); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static MemorySegment msgcore_field_get_wstr(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_field_get_wstr.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static void msgcore_field_set_wstr(MemorySegment hField, MemorySegment value) {
        try { MH_msgcore_field_set_wstr.invokeExact(hField, value); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_list(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_list.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_vect(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_vect.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_attributed(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_attributed.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_field_is_descendant(MemorySegment hField) {
        try { return (int) MH_msgcore_field_is_descendant.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    // List
    public static MemorySegment msgcore_list_from_field(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_list_from_field.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_destroy(MemorySegment h) {
        try { MH_msgcore_list_destroy.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_list_get_count(MemorySegment h) {
        try { return (int) MH_msgcore_list_get_count.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_tail_int(MemorySegment h, int v) {
        try { MH_msgcore_list_add_tail_int.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_head_int(MemorySegment h, int v) {
        try { MH_msgcore_list_add_head_int.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_tail_double(MemorySegment h, double v) {
        try { MH_msgcore_list_add_tail_double.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_head_double(MemorySegment h, double v) {
        try { MH_msgcore_list_add_head_double.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_tail_wstr(MemorySegment h, MemorySegment v) {
        try { MH_msgcore_list_add_tail_wstr.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_add_head_wstr(MemorySegment h, MemorySegment v) {
        try { MH_msgcore_list_add_head_wstr.invokeExact(h, v); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_drop_head(MemorySegment h) {
        try { MH_msgcore_list_drop_head.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_drop_tail(MemorySegment h) {
        try { MH_msgcore_list_drop_tail.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_list_truncate(MemorySegment h) {
        try { MH_msgcore_list_truncate.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    // Vect
    public static MemorySegment msgcore_vect_from_field(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_vect_from_field.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_vect_destroy(MemorySegment h) {
        try { MH_msgcore_vect_destroy.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_vect_is_data(MemorySegment h, int n) {
        try { return (int) MH_msgcore_vect_is_data.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_vect_is_field(MemorySegment h, int n) {
        try { return (int) MH_msgcore_vect_is_field.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_vect_is_list(MemorySegment h, int n) {
        try { return (int) MH_msgcore_vect_is_list.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_vect_is_vect(MemorySegment h, int n) {
        try { return (int) MH_msgcore_vect_is_vect.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_vect_get_int(MemorySegment h, int n) {
        try { return (int) MH_msgcore_vect_get_int.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static double msgcore_vect_get_double(MemorySegment h, int n) {
        try { return (double) MH_msgcore_vect_get_double.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_vect_get_wstr(MemorySegment h, int n) {
        try { return (MemorySegment) MH_msgcore_vect_get_wstr.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_vect_get_item(MemorySegment h, int n) {
        try { return (MemorySegment) MH_msgcore_vect_get_item.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_vect_truncate(MemorySegment h) {
        try { MH_msgcore_vect_truncate.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    // Attr
    public static MemorySegment msgcore_attr_from_field(MemorySegment hField, int bCreate) {
        try { return (MemorySegment) MH_msgcore_attr_from_field.invokeExact(hField, bCreate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_attr_destroy(MemorySegment h) {
        try { MH_msgcore_attr_destroy.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_attr_get_count(MemorySegment h) {
        try { return (int) MH_msgcore_attr_get_count.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_attr_is_empty(MemorySegment h) {
        try { return (int) MH_msgcore_attr_is_empty.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_attr_exists(MemorySegment h, MemorySegment name) {
        try { return (int) MH_msgcore_attr_exists.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_attr_select_item(MemorySegment h, MemorySegment name) {
        try { return (MemorySegment) MH_msgcore_attr_select_item.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_attr_declare_int(MemorySegment h, MemorySegment name, int v, int upd) {
        try { return (MemorySegment) MH_msgcore_attr_declare_int.invokeExact(h, name, v, upd); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_attr_declare_double(MemorySegment h, MemorySegment name, double v, int upd) {
        try { return (MemorySegment) MH_msgcore_attr_declare_double.invokeExact(h, name, v, upd); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_attr_declare_wstr(MemorySegment h, MemorySegment name, MemorySegment v, int upd) {
        try { return (MemorySegment) MH_msgcore_attr_declare_wstr.invokeExact(h, name, v, upd); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_attr_delete(MemorySegment h, MemorySegment name) {
        try { return (int) MH_msgcore_attr_delete.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_attr_truncate(MemorySegment h) {
        try { MH_msgcore_attr_truncate.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    // Desc
    public static MemorySegment msgcore_desc_from_field(MemorySegment hField, int bCreate) {
        try { return (MemorySegment) MH_msgcore_desc_from_field.invokeExact(hField, bCreate); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_desc_destroy(MemorySegment h) {
        try { MH_msgcore_desc_destroy.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_desc_get_count(MemorySegment h) {
        try { return (int) MH_msgcore_desc_get_count.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_desc_is_empty(MemorySegment h) {
        try { return (int) MH_msgcore_desc_is_empty.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_desc_exists(MemorySegment h, MemorySegment name) {
        try { return (int) MH_msgcore_desc_exists.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_desc_select_item(MemorySegment h, MemorySegment name) {
        try { return (MemorySegment) MH_msgcore_desc_select_item.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_desc_declare_int(MemorySegment h, MemorySegment name, int v, int upd) {
        try { return (MemorySegment) MH_msgcore_desc_declare_int.invokeExact(h, name, v, upd); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_desc_declare_wstr(MemorySegment h, MemorySegment name, MemorySegment v, int upd) {
        try { return (MemorySegment) MH_msgcore_desc_declare_wstr.invokeExact(h, name, v, upd); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_desc_delete(MemorySegment h, MemorySegment name) {
        try { return (int) MH_msgcore_desc_delete.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_desc_truncate(MemorySegment h) {
        try { MH_msgcore_desc_truncate.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    // Curs
    public static MemorySegment msgcore_curs_from_field(MemorySegment hField) {
        try { return (MemorySegment) MH_msgcore_curs_from_field.invokeExact(hField); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_curs_from_attr(MemorySegment hAttr) {
        try { return (MemorySegment) MH_msgcore_curs_from_attr.invokeExact(hAttr); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_curs_from_desc(MemorySegment hDesc) {
        try { return (MemorySegment) MH_msgcore_curs_from_desc.invokeExact(hDesc); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_curs_destroy(MemorySegment h) {
        try { MH_msgcore_curs_destroy.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_curs_next(MemorySegment h) {
        try { MH_msgcore_curs_next.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_curs_seek(MemorySegment h) {
        try { MH_msgcore_curs_seek.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_goto_name(MemorySegment h, MemorySegment name) {
        try { return (int) MH_msgcore_curs_goto_name.invokeExact(h, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_goto_index(MemorySegment h, int n) {
        try { return (int) MH_msgcore_curs_goto_index.invokeExact(h, n); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_is_eo_cursor(MemorySegment h) {
        try { return (int) MH_msgcore_curs_is_eo_cursor.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_is_so_cursor(MemorySegment h) {
        try { return (int) MH_msgcore_curs_is_so_cursor.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_get_count(MemorySegment h) {
        try { return (int) MH_msgcore_curs_get_count.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_item_index(MemorySegment h) {
        try { return (int) MH_msgcore_curs_item_index.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_is_item(MemorySegment h) {
        try { return (int) MH_msgcore_curs_is_item.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_is_list(MemorySegment h) {
        try { return (int) MH_msgcore_curs_is_list.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static int msgcore_curs_is_vect(MemorySegment h) {
        try { return (int) MH_msgcore_curs_is_vect.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_curs_get_field(MemorySegment h) {
        try { return (MemorySegment) MH_msgcore_curs_get_field.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static MemorySegment msgcore_curs_get_name(MemorySegment h) {
        try { return (MemorySegment) MH_msgcore_curs_get_name.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
    public static void msgcore_curs_delete(MemorySegment h) {
        try { MH_msgcore_curs_delete.invokeExact(h); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }

    public static int msgcore_wildcard_match(MemorySegment wildcard, MemorySegment name) {
        try { return (int) MH_msgcore_wildcard_match.invokeExact(wildcard, name); }
        catch (Throwable t) { throw new RuntimeException(t); }
    }
}
