// Generated by jextract

package com.p2pmsgcore.native_;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*P2PeerHubSinkFnU8)(void *, const char *, const char *, const char *, const void *, int64_t)
 * }
 */
public final class P2PeerHubSinkFnU8 {

    private P2PeerHubSinkFnU8() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment ctx, MemorySegment srcAddr, MemorySegment dstAddr, MemorySegment msgID, MemorySegment data, long dataSize);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        P2Pmsgcore_c.C_INT,
        P2Pmsgcore_c.C_POINTER,
        P2Pmsgcore_c.C_POINTER,
        P2Pmsgcore_c.C_POINTER,
        P2Pmsgcore_c.C_POINTER,
        P2Pmsgcore_c.C_POINTER,
        P2Pmsgcore_c.C_LONG_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = P2Pmsgcore_c.upcallHandle(P2PeerHubSinkFnU8.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(P2PeerHubSinkFnU8.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment ctx, MemorySegment srcAddr, MemorySegment dstAddr, MemorySegment msgID, MemorySegment data, long dataSize) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, ctx, srcAddr, dstAddr, msgID, data, dataSize);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

